package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.68

import (
	"context"
	"fmt"

	"github.com/subhammurarka/GraphQL/graph/model"
	"github.com/subhammurarka/GraphQL/graph/validate"
	"github.com/vektah/gqlparser/gqlerror"
)

// BestMaterial is the resolver for the bestMaterial field.
func (r *queryResolver) BestMaterial(ctx context.Context, request model.UserRequest) (*model.UserResponse, error) {
	// checking validity for materialtype
	if err := validate.ValidateMaterialType(request.MaterialType); err != nil {
		return nil, gqlerror.Errorf("input validation failed : %v", err)
	}

	//checking validity for location
	if err := validate.ValidateLocality(request.Locality); err != nil {
		return nil, gqlerror.Errorf("input validation failed : %v", err)
	}

	materialRepo, supplierRepo, err := r.MaterialSvc.GetMaterialAndSupplier(request.MaterialType, request.Price, request.Locality)
	if err != nil {
		return nil, gqlerror.Errorf("failed to fetch the details : %v", err)
	}

	fmt.Println("materialRepo: ", materialRepo, "\n\n SupplierRepo", supplierRepo)

	Supplier := &model.Supplier{
		ID:                int32(supplierRepo.ID),
		SupplierName:      supplierRepo.SupplierName,
		SupplierLocation:  supplierRepo.SupplierLocation,
		StockAvailability: supplierRepo.StockAvailability,
	}

	resp := &model.UserResponse{
		Material: (*model.Material)(&materialRepo),
		Supplier: Supplier,
	}

	return resp, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
