// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Material struct {
	ID           int32   `json:"id"`
	MaterialName string  `json:"materialName"`
	MaterialType string  `json:"materialType"`
	Price        float64 `json:"price"`
	Rating       int32   `json:"rating"`
	Quality      int32   `json:"Quality"`
}

type Query struct {
}

type Supplier struct {
	ID                int32  `json:"id"`
	SupplierName      string `json:"supplierName"`
	SupplierLocation  string `json:"supplierLocation"`
	StockAvailability string `json:"stockAvailability"`
}

type UserRequest struct {
	MaterialType string  `json:"materialType"`
	Price        float64 `json:"price"`
	Locality     string  `json:"locality"`
}

type UserResponse struct {
	Material *Material `json:"material"`
	Supplier *Supplier `json:"supplier"`
}
